#!/bin/bash
# Build OpenOCD for macOS aarch64.
# Run this script from the repository root.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="${ROOT}/build"
DIST_NAME="openocd-macos-aarch64"
DIST_DIR="${ROOT}/${DIST_NAME}"

# Ensure Homebrew tools are on PATH
export PATH="/opt/homebrew/bin:${PATH}"

echo "==> Installing dependencies via Homebrew..."
brew install --quiet autoconf automake libtool pkg-config libusb hidapi || true

cd "${ROOT}"

echo "==> Regenerating autotools build system..."
# jimtcl uses an autosetup wrapper for configure. autoreconf will overwrite it
# with a dummy autoconf-generated configure, so keep a backup.
if grep -q autosetup jimtcl/configure; then
    cp jimtcl/configure jimtcl/configure.autosetup.bak
fi

autoreconf -fi

if [[ -f jimtcl/configure.autosetup.bak ]]; then
    cp jimtcl/configure.autosetup.bak jimtcl/configure
    rm -f jimtcl/configure.autosetup.bak
fi

echo "==> Fixing generated wrapper and permissions..."
# The configure.gnu generated by AX_CONFIG_SUBDIR_OPTION is not portable on
# macOS /bin/sh (the leading '-e' is printed literally). Rewrite it.
cat > jimtcl/configure.gnu <<'EOF'
#!/bin/sh
exec "`dirname "$0"`/configure" --disable-install-jim --with-ext=json "$@"
EOF
chmod +x jimtcl/configure.gnu

# Restore executable bits that are often lost when the source is imported.
chmod +x configure jimtcl/configure jimtcl/configure.gnu
chmod +x build-aux/* src/jtag/drivers/libjaylink/build-aux/*
chmod +x src/helper/bin2char.sh contrib/cross-build.sh jimtcl/make-release.sh
chmod +x jimtcl/autosetup/autosetup \
          jimtcl/autosetup/autosetup-find-tclsh \
          jimtcl/autosetup/autosetup-test-tclsh
find . -name "*.sh" -not -path "./.git/*" -not -path "./build/*" -exec chmod +x {} +

echo "==> Configuring..."
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"
../configure --disable-werror --disable-dependency-tracking --enable-cmsis-dap

echo "==> Building..."
make -j"$(sysctl -n hw.ncpu)"

cd "${ROOT}"

echo "==> Packaging..."
rm -rf "${DIST_DIR}"
mkdir -p "${DIST_DIR}/bin"
mkdir -p "${DIST_DIR}/openocd/scripts"
mkdir -p "${DIST_DIR}/share/doc"

cp "${BUILD_DIR}/src/openocd" "${DIST_DIR}/bin/"
chmod +x "${DIST_DIR}/bin/openocd"

cp -R "${ROOT}/tcl/"* "${DIST_DIR}/openocd/scripts/"

cp "${ROOT}/README" "${DIST_DIR}/"
cp -R "${ROOT}/LICENSES" "${DIST_DIR}/"

# Copy available documentation (info files are usually prebuilt in the repo).
for f in openocd.info openocd.info-1 openocd.info-2 openocd.texi openocd.1 checkpatch.rst; do
    [[ -f "${ROOT}/doc/${f}" ]] && cp "${ROOT}/doc/${f}" "${DIST_DIR}/share/doc/"
done

echo "==> Creating tarball ${DIST_NAME}.tar.gz..."
tar -czf "${DIST_NAME}.tar.gz" "${DIST_NAME}"

echo "==> Done."
echo "    Binary: ${DIST_DIR}/bin/openocd"
echo "    Tarball: ${ROOT}/${DIST_NAME}.tar.gz"
